### ISSUE TITLE
Phase 3 - Extra Credit, Example 4 "a b c d e f" incorrect

### ISSUE THREAD

**Issue by mshenfield** [makersquare/admissions-challenge#2]
Hey, I've been looking into the program for a cousin.  It looks amazing!

I noticed there was a bug in the last example for [Phase 3 - Extra Credit](https://github.com/makersquare/admissions-challenge#user-content-phase-3---extra-credit).  The example returns the 3rd character of the 4th word instead of the 4th character for the last example "a b c d e f" => "acf".

In the outline of the problem, and the other examples, n is defined as the index of the word in the sentence.  So for the first word, take the 1st letter, the 4th word, take the 4th letter.  In this last example, it looks like n is confused as the index of the letter in the secret message.  So if you consumed an extra word for the 2nd secret character output, as in example 1 "oh i understand banter", you'd incorrectly pull the 3rd letter of the 4th word instead of the 4th.

This could be corrected by changing the example to "a b c d e f g" => "acg"

**Comment by harshpatel** [comment]
Thanks for the feedback!

**Comment by mshenfield** [comment]
Saw you all pushed up your own fix.  Within an hour on a Sunday. Well done!

**Comment by harshpatel** [comment]
:+1:
